config/routes.rb
SeminarverwaltungRails3::Application.routes.draw do |map|
  resources :teilnahmen

  resources :benutzer

  resources :seminars do
    resources :seminartermine
  end
  
  resources :seminartermine

end

app/models/benutzer.rb
class Benutzer < ActiveRecord::Base
  has_many :teilnahmen

  searchable_on :vorname, :name, :email

  validates_presence_of :vorname, :name, :anrede

  def to_s
    "#{anrede} #{vorname} #{name}"
  end
end

app/models/seminar.rb
class Seminar < ActiveRecord::Base
  has_friendly_id :titel, :use_slug => true, :approximate_ascii => true,
    :ascii_approximation_options => :german

  has_many :seminartermine

  searchable_on :titel, :beschreibung, :preis, :kategorie,
    :seminartermine_raum, :seminartermine_beginn, :seminartermine_ende

  default_scope :include => :seminartermine 

  validates_presence_of :titel, :preis
  validates_numericality_of :preis

  def to_s
    "Seminar '#{titel}'"
  end
end

app/models/seminartermin.rb
class Seminartermin < ActiveRecord::Base
  has_friendly_id :description, :use_slug => true, :approximate_ascii => true,
    :ascii_approximation_options => :german

  belongs_to :seminar, :counter_cache => :seminartermine_count
  has_many :teilnahmen
  has_many :teilnehmer, :through => :teilnahmen, :source => :benutzer, :class_name => "Benutzer"

  searchable_on :beginn, :ende, :raum, :teilnehmer_vorname, :teilnehmer_name, 
    :teilnehmer_email, :seminar_titel, :seminar_beschreibung, :seminar_kategorie,
    :seminar_preis

  default_scope :include => [:seminar, :teilnehmer]

  def description
    "#{seminar.titel} vom #{beginn} bis #{ende} in #{raum}"
  end

  def to_s
    description
  end
end

app/models/teilnahme.rb
class Teilnahme < ActiveRecord::Base
  belongs_to :seminartermin
  belongs_to :benutzer

  delegate :seminar, :beginn, :ende, :raum, :to => :seminartermin
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  layout 'application'
end

app/controllers/benutzer_controller.rb
class BenutzerController < InheritedResources::Base

  has_scope :search_for

  private
  def collection
    @benutzer ||= end_of_association_chain.paginate(
      :page => params[:page], :per_page => 15)
  end
end

app/controllers/seminars_controller.rb
class SeminarsController < InheritedResources::Base

  has_scope :search_for

  private
  def collection
    @seminars ||= end_of_association_chain.paginate(
      :page => params[:page], :per_page => 15)
  end
end

app/controllers/seminartermine_controller.rb
class SeminartermineController < InheritedResources::Base
  optional_belongs_to :seminar
  respond_to :json, :only => [:index, :show]
  respond_to :js, :only => :index

  has_scope :search_for

  private
  def collection
    @seminartermine ||= end_of_association_chain.paginate(
      :page => params[:page], :per_page => 15)
  end
end

app/controllers/teilnahmen_controller.rb
class TeilnahmenController < InheritedResources::Base
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/benutzer_helper.rb
module BenutzerHelper
end

app/helpers/seminars_helper.rb
module SeminarsHelper
end

app/helpers/seminartermine_helper.rb
module SeminartermineHelper
end

app/helpers/teilnahmen_helper.rb
module TeilnahmenHelper
end

app/views/benutzer/_form.html.erb
<%= semantic_form_for(@benutzer) do |f| %>
  <% f.inputs do %>
    <%= f.input :anrede, :label => 'Anrede' %>
    <%= f.input :vorname, :label => 'Vorname' %>
    <%= f.input :name, :label => 'Name' %>
    <%= f.input :email, :label => 'Email' %>
  <% end %>

  <%= f.buttons %>
<% end %>

app/views/benutzer/edit.html.erb
<h1>Editing benutzer</h1>

<%= render 'form' %>

<%= link_to 'Show', @benutzer %> |
<%= link_to 'Back', benutzer_path %>

app/views/benutzer/index.html.erb
<h1>Listing benutzer</h1>

<%= form_tag({:action => :index}, :method => :get) do %>
  <%= text_field_tag :search_for %>
  <%= submit_tag "Suche" %>
<% end %>

<%= table_for @benutzer do |t|
  t.data :actions => :all do
    t.data :anrede, :vorname, :name, :email
  end
end %>

<%= will_paginate @benutzer %>

<%= link_to 'New Benutzer', new_benutzer_path %>

app/views/benutzer/new.html.erb
<h1>New benutzer</h1>

<%= render 'form' %>

<%= link_to 'Back', benutzer_path %>

app/views/benutzer/show.html.erb
<% show_for @benutzer do |o| %>
  <%= o.attribute :anrede %>
  <%= o.attribute :vorname %>
  <%= o.attribute :name %>
  <%= o.attribute :email %>
<% end %>

<%= link_to 'Edit', edit_benutzer_path(@benutzer) %> |
<%= link_to 'Back', :action => 'index' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Seminarverwaltung mit Rails3</title>
    <%= stylesheet_link_tag 'blueprint/screen', :media => "screen, projection" %>
    <%= stylesheet_link_tag 'blueprint/plugins/link-icons/screen', :media => "screen, projection" %>
    <%= stylesheet_link_tag 'blueprint/plugins/fancy-type/screen', :media => "screen, projection" %>
    <%= stylesheet_link_tag 'blueprint/print', :media => "print" %>

    <!--[if lt IE 8]>
    <%= stylesheet_link_tag 'blueprint/ie', :media => "screen, projection" %>
    <![endif]-->

    <%= stylesheet_link_tag :all %>
    <%= javascript_include_tag :defaults %>

    <%= csrf_meta_tag %>
  </head>
  <body>

    <div class="container">
      <div id="header" class="span-24 last">
        <h1>Seminarverwaltung mit Rails 3</h1>
      </div>

      <div id="navigation" class="span-4">
        <h3>Navigation</h3>
        <ul>
          <li><%= link_to "Seminare", seminars_path %></li>
          <li><%= link_to "Seminartermine", seminartermine_path %></li>
          <li><%= link_to "Benutzer", :controller => 'benutzer', :action => 'index' %></li>
          <li><%= link_to "Teilnahmen", teilnahmen_path %></li>
        </ul>
      </div>

      <div id="content" class="span-20 last">
        <%= yield %>
      </div>

      <div id="header" class="span-24 last">
        <p>Das Ende</p>
      </div>

    </div>

  </body>
</html>

app/views/seminars/_form.html.erb
<% semantic_form_for @seminar do |f| %>

  <% f.inputs "Allgemein" do %>
    <%= f.input :titel, :label => 'Titel' %>
    <%= f.input :preis, :label => 'Preis' %>
    <%= f.input :kategorie, :label => 'Kategorie' %>
  <% end %>

  <% f.inputs "Beschreibung" do %>
    <%= f.input :beschreibung, :label => 'Beschreibung' %>
  <% end %>

  <%= f.buttons %>

<% end %>

app/views/seminars/edit.html.erb
<h2>Editing seminar</h2>

<%= render 'form' %>

<%= link_to 'Show', @seminar %> |
<%= link_to 'Back', seminars_path %>

app/views/seminars/index.html.erb
<h2>Listing seminars</h2>

<%= render :partial => '/search' %>

<%= table_for @seminars do |t|
  t.data :actions => :all do
    t.data :titel, :cached_slug, :preis, :kategorie
    t.cell(:seminartermine) do |s|
      link_text = raw((s.seminartermine.collect {|st| "#{st.beginn} - #{st.ende}"}).join(',<br />'))
      link_to link_text, :controller => 'seminartermine', :action => 'index',
        :seminar_id => s.cached_slug unless s.seminartermine.blank?
    end
  end
end %>

<%= will_paginate @seminars %>

<%= link_to 'New Seminar', new_seminar_path %>

app/views/seminars/new.html.erb
<h2>New seminar</h2>

<%= render 'form' %>

<%= link_to 'Back', seminars_path %>

app/views/seminars/show.html.erb
<h2>Show seminar</h2>

<% show_for @seminar do |o| %>
  <%= o.attribute :titel %>
  <%= o.attribute :beschreibung %>
  <%= o.attribute :preis %>
  <%= o.attribute :kategorie %>
<% end %>

<%= link_to 'Edit', edit_seminar_path(@seminar) %> |
<%= link_to 'Back', seminars_path %>

app/views/seminartermine/_form.html.erb
<% semantic_form_for @seminartermin do |f| %>
  <% f.inputs do %>
    <%= f.input :seminar, :label => 'Seminar' %>
    <%= f.input :beginn, :label => 'Beginn' %>
    <%= f.input :ende, :label => 'Ende' %>
    <%= f.input :raum, :label => 'Raum' %>
  <% end %>

<%= f.buttons %>
<% end %>

app/views/seminartermine/_tabelle.html.erb
<%= table_for(@seminartermine) do |t|
  t.data :actions => :all do
    t.data :beginn, :ende, :raum
    t.cell :seminar do |s|
      link_to s.seminar, edit_seminar_path(s.seminar)
    end

    t.cell :teilnehmer do |s|
      raw(s.teilnehmer.collect {|t| link_to t.to_s, edit_benutzer_path(t) }.join('<br />'))
    end
  end
end %>

app/views/seminartermine/edit.html.erb
<h2>Editing seminartermin</h2>

<%= render 'form' %>

<%= link_to 'Show', @seminartermin %> |
<%= link_to 'Back', seminartermine_path %>

app/views/seminartermine/index.html.erb
<h2>Listing seminartermine</h2>

<%= render :partial => '/search' %>

<%= render :partial => 'tabelle', :locals => {:seminartermine => @seminartermine} %>

<%= will_paginate @seminartermine %>

<%= link_to 'New Seminartermin', new_seminartermin_path %>

app/views/seminartermine/index.js.erb
<%= render :partial => 'tabelle', :locals => {:seminartermine => @seminartermine} %>

app/views/seminartermine/new.html.erb
<h2>New seminartermin</h2>

<%= render 'form' %>

<%= link_to 'Back', seminartermine_path %>

app/views/seminartermine/show.html.erb
<h2>Show seminartermin</h2>

<% show_for @seminartermin do |o| %>
  <%= o.attribute :beginn %>
  <%= o.attribute :ende %>
  <%= o.attribute :raum %>
  <%= o.association :seminar %>
<% end %>

<%= link_to 'Edit', edit_seminartermin_path(@seminartermin) %> |
<%= link_to 'Back', seminartermine_path %>

app/views/teilnahmen/_form.html.erb
<%= semantic_form_for(@teilnahme) do |f| %>
  <% f.inputs do %>
    <%= f.input :seminartermin, :label => 'Seminartermin' %>
    <%= f.input :benutzer, :label => 'Teilnehmer' %>
  <% end %>
  <%= f.buttons %>
<% end %>

app/views/teilnahmen/edit.html.erb
<h1>Editing teilnahme</h1>

<%= render 'form' %>

<%= link_to 'Show', @teilnahme %> |
<%= link_to 'Back', teilnahmen_path %>

app/views/teilnahmen/index.html.erb
<h1>Listing teilnahmen</h1>

<%= table_for @teilnahmen do |t|
  t.data :actions => :all do
    t.data :seminar, :beginn, :ende, :raum
    t.cell(:benutzer) {|t| t.benutzer.to_s }
  end
end %>

<%= link_to 'New Teilnahme', new_teilnahme_path %>

app/views/teilnahmen/new.html.erb
<h1>New teilnahme</h1>

<%= render 'form' %>

<%= link_to 'Back', teilnahmen_path %>

app/views/teilnahmen/show.html.erb
<% show_for @teilnahme do |o| %>
  <%= o.association :seminartermin %>
  <%= o.association :benutzer %>
<% end %>

<%= link_to 'Edit', edit_teilnahme_path(@teilnahme) %> |
<%= link_to 'Back', teilnahmen_path %>